"""Docs publish — build a static docs site from the component mirror.

Dev Lane only. Generates a self-contained static HTML site from
``~/.ucore/docs-mirror/`` into ``~/Public/doc-sites/udos-docs/`` and
optionally deploys it (git commit + push) to ``docs.udo.guide``.

This module never touches user-lane vault paths.
"""
from __future__ import annotations

import html
import json
import re
import shutil
import subprocess
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from app.core.logging import log

SITE_ROOT = Path.home() / "Public" / "doc-sites" / "udos-docs"
STATUS_FILE = "publish.json"

SITE_TITLE = "uDos Documentation"
SITE_DESCRIPTION = "Component documentation for the uDos ecosystem, mirrored from in-repo docs/ directories."


# ─── Markdown rendering (stdlib only) ─────────────────────────────

_INLINE = (
    (re.compile(r"\*\*(.+?)\*\*"), r"<strong>\1</strong>"),
    (re.compile(r"`([^`\n]+)`"), r"<code>\1</code>"),
    (re.compile(r"\*([^*\n]+)\*"), r"<em>\1</em>"),
    (re.compile(r"\[([^\]]+)\]\(([^)\s]+)\)"), r'<a href="\2">\1</a>'),
)


def _inline(text: str) -> str:
    for pattern, repl in _INLINE:
        text = pattern.sub(repl, text)
    return text


def markdown_to_html(md: str) -> str:
    """Render a small, safe subset of Markdown to HTML."""
    lines = md.split("\n")
    out: list[str] = []
    in_code = False
    code_buf: list[str] = []
    list_buf: list[str] = []
    para_buf: list[str] = []

    def flush_para() -> None:
        nonlocal para_buf
        if para_buf:
            out.append("<p>" + " ".join(_inline(p) for p in para_buf) + "</p>")
            para_buf = []

    def flush_list() -> None:
        nonlocal list_buf
        if list_buf:
            out.append("<ul>" + "".join(f"<li>{_inline(i)}</li>" for i in list_buf) + "</ul>")
            list_buf = []

    for line in lines:
        if line.strip().startswith("```"):
            flush_para()
            flush_list()
            if in_code:
                out.append("<pre><code>" + html.escape("\n".join(code_buf)) + "</code></pre>")
                code_buf = []
            in_code = not in_code
            continue
        if in_code:
            code_buf.append(line)
            continue

        stripped = line.strip()
        if not stripped:
            flush_para()
            flush_list()
            continue

        heading = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if heading:
            flush_para()
            flush_list()
            level = len(heading.group(1))
            out.append(f"<h{level}>{_inline(heading.group(2))}</h{level}>")
            continue

        if re.match(r"^[-*+]\s+", stripped):
            flush_para()
            list_buf.append(stripped[2:].strip())
            continue

        if stripped.startswith("&gt; ") or stripped.startswith("> "):
            flush_para()
            flush_list()
            out.append(f"<blockquote>{_inline(stripped[2:].strip())}</blockquote>")
            continue

        para_buf.append(line.strip())

    flush_para()
    flush_list()
    if in_code and code_buf:
        out.append("<pre><code>" + html.escape("\n".join(code_buf)) + "</code></pre>")
    return "\n".join(out)


# ─── Static site generation ───────────────────────────────────────

def _page(title: str, body: str, crumb: str = "") -> str:
    header = (
        '<header class="site-header">'
        f'<a class="site-home" href="/udos-docs/">uDos Docs</a>'
        f"<span class=\"site-crumb\">{html.escape(crumb)}</span>"
        "</header>"
    )
    return (
        "<!DOCTYPE html><html lang=\"en\"><head>"
        f"<meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
        f"<title>{html.escape(title)} — {html.escape(SITE_TITLE)}</title>"
        '<link rel="stylesheet" href="/udos-docs/assets/style.css">'
        "</head><body>"
        f"{header}<main class=\"site-main\">{body}</main>"
        '<footer class="site-footer">Generated by uCore docs-publish.</footer>'
        "</body></html>"
    )


def _css() -> str:
    return """\
:root {
  --usx-color-background: #0f1217;
  --usx-color-surface: #171b22;
  --usx-color-surface-variant: #1f242e;
  --usx-color-on-surface: #e6e9ef;
  --usx-color-on-surface-muted: #9aa3b2;
  --usx-color-border: #2a303c;
  --usx-color-primary: #58a6ff;
  --usx-color-success: #3fb950;
  --usx-color-warning: #d29922;
  --usx-color-danger: #f85149;
  --usx-font-family-sans: system-ui, -apple-system, "Segoe UI", sans-serif;
  --usx-font-family-mono: ui-monospace, "SF Mono", Menlo, monospace;
}
@media (prefers-color-scheme: light) {
  :root {
    --usx-color-background: #ffffff;
    --usx-color-surface: #f6f8fa;
    --usx-color-surface-variant: #eef1f4;
    --usx-color-on-surface: #1f2328;
    --usx-color-on-surface-muted: #59636e;
    --usx-color-border: #d0d7de;
    --usx-color-primary: #0969da;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0;
  font-family: var(--usx-font-family-sans);
  background: var(--usx-color-background);
  color: var(--usx-color-on-surface);
  line-height: 1.6;
}
.site-header, .site-footer {
  padding: 0.9rem 1.5rem;
  background: var(--usx-color-surface);
  border-bottom: 1px solid var(--usx-color-border);
  display: flex; gap: 0.75rem; align-items: center;
}
.site-footer { border-top: 1px solid var(--usx-color-border); border-bottom: none; }
.site-home { color: var(--usx-color-primary); font-weight: 600; text-decoration: none; }
.site-crumb { color: var(--usx-color-on-surface-muted); font-size: 0.9rem; }
.site-main { max-width: 72rem; margin: 0 auto; padding: 1.5rem; }
h1, h2, h3, h4 { line-height: 1.3; margin: 1.25rem 0 0.5rem; }
h1 { border-bottom: 1px solid var(--usx-color-border); padding-bottom: 0.4rem; }
a { color: var(--usx-color-primary); }
code, pre {
  font-family: var(--usx-font-family-mono);
  background: var(--usx-color-surface-variant);
  border-radius: 4px;
}
code { padding: 0.1rem 0.35rem; font-size: 0.9em; }
pre { padding: 0.9rem; overflow-x: auto; }
pre code { padding: 0; background: none; }
blockquote {
  margin: 0.75rem 0; padding: 0.4rem 1rem;
  border-left: 3px solid var(--usx-color-border);
  color: var(--usx-color-on-surface-muted);
}
.repo-card, .doc-row {
  display: block; padding: 0.75rem 1rem; margin: 0.4rem 0;
  background: var(--usx-color-surface);
  border: 1px solid var(--usx-color-border);
  border-radius: 8px; text-decoration: none; color: var(--usx-color-on-surface);
}
.repo-card:hover, .doc-row:hover { border-color: var(--usx-color-primary); }
.doc-row code { float: right; }
.meta { color: var(--usx-color-on-surface-muted); font-size: 0.85rem; }
.badge { color: var(--usx-color-success); }
"""


def _slug(path: str) -> str:
    return re.sub(r"[^a-zA-Z0-9._/-]+", "-", path)


def build_site(mirror_root: Path | None = None, site_root: Path | None = None) -> dict[str, Any]:
    """Build the static site from the mirror. Returns status summary."""
    mirror = mirror_root or (Path.home() / ".ucore" / "docs-mirror")
    root = site_root or SITE_ROOT

    index_file = mirror / "_mirror.json"
    if not index_file.exists():
        return {"status": "error", "error": f"Mirror index missing: {index_file}"}

    index = json.loads(index_file.read_text(encoding="utf-8"))
    entries = index.get("entries", [])

    docs_dir = root / "docs"
    assets_dir = root / "assets"
    docs_dir.mkdir(parents=True, exist_ok=True)
    assets_dir.mkdir(parents=True, exist_ok=True)

    # Copy raw markdown for each repo.
    by_repo: dict[str, list[dict[str, Any]]] = {}
    for entry in entries:
        repo = entry.get("source_repo", "?")
        by_repo.setdefault(repo, []).append(entry)

    rendered = 0
    for repo, repo_entries in sorted(by_repo.items()):
        repo_dir = docs_dir / repo
        repo_dir.mkdir(parents=True, exist_ok=True)
        repo_rows: list[str] = []
        for entry in sorted(repo_entries, key=lambda e: str(e.get("source_path", "")).lower()):
            src = mirror / entry["mirrored_path"]
            if not src.is_file():
                continue
            rel = entry["source_path"]
            rel_html = rel[:-3] + ".html" if rel.endswith(".md") else rel + ".html"

            # Raw markdown copy.
            dest_md = docs_dir / repo / rel
            dest_md.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dest_md)

            # Rendered HTML page.
            content = src.read_text(encoding="utf-8", errors="replace")
            body = markdown_to_html(content)
            page = _page(rel, body, f"{repo} / {rel}")
            dest_html = docs_dir / repo / rel_html
            dest_html.parent.mkdir(parents=True, exist_ok=True)
            dest_html.write_text(page, encoding="utf-8")
            rendered += 1

            repo_rows.append(
                f'<a class="doc-row" href="/udos-docs/docs/{repo}/{_slug(rel_html)}">'
                f"<code>{_slug(rel)}</code>{html.escape(rel)}</a>"
            )

        repo_page = _page(
            f"{repo} — {len(repo_rows)} docs",
            f"<h1>{repo}</h1><p class=\"meta\">{len(repo_rows)} documents</p>" + "\n".join(repo_rows),
            repo,
        )
        (docs_dir / repo / "index.html").write_text(repo_page, encoding="utf-8")

    # Home page.
    repo_cards = []
    for repo, repo_entries in sorted(by_repo.items()):
        repo_cards.append(
            f'<a class="repo-card" href="/udos-docs/docs/{_slug(repo)}/">'
            f"<strong>{html.escape(repo)}</strong>"
            f'<span class="meta"> · {len(repo_entries)} docs</span></a>'
        )
    home = _page(
        SITE_TITLE,
        f"<h1>{SITE_TITLE}</h1><p>{SITE_DESCRIPTION}</p>"
        f'<p class="meta">Mirrored at {index.get("synced_at", "?")} · {len(entries)} files</p>'
        + "\n".join(repo_cards),
    )
    (root / "index.html").write_text(home, encoding="utf-8")

    (assets_dir / "style.css").write_text(_css(), encoding="utf-8")

    # Sitemap.
    sitemap_rows = ["<li><a href=\"/udos-docs/\">Home</a></li>"]
    for repo in sorted(by_repo):
        sitemap_rows.append(f"<li><a href=\"/udos-docs/docs/{_slug(repo)}/\">{html.escape(repo)}</a></li>")
    (root / "sitemap.html").write_text(
        _page("Sitemap", "<h1>Sitemap</h1><ul>" + "".join(sitemap_rows) + "</ul>"),
        encoding="utf-8",
    )

    built_at = datetime.now(UTC).isoformat()
    status = {
        "status": "ok",
        "built_at": built_at,
        "site_root": str(root),
        "total_files": len(entries),
        "rendered_pages": rendered,
        "repos": {repo: len(items) for repo, items in sorted(by_repo.items())},
    }
    (root / STATUS_FILE).write_text(json.dumps(status, indent=2), encoding="utf-8")
    log.info("Docs site built: %d pages at %s", rendered, root)
    return status


def publish_status(site_root: Path | None = None) -> dict[str, Any]:
    """Return the last publish status."""
    root = site_root or SITE_ROOT
    path = root / STATUS_FILE
    if not path.exists():
        return {"status": "not-built", "site_root": str(root)}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {"status": "error", "site_root": str(root)}


def deploy_site(site_root: Path | None = None) -> dict[str, Any]:
    """Deploy the built site via git (commit + push) if it is a git repo."""
    root = site_root or SITE_ROOT
    if not (root / ".git").exists():
        return {"deployed": False, "reason": "site_root is not a git repository"}

    def _run(args: list[str]) -> dict[str, Any]:
        proc = subprocess.run(
            ["git", "-C", str(root), *args],
            capture_output=True,
            text=True,
            timeout=60,
        )
        return {
            "cmd": " ".join(args),
            "exit_code": proc.returncode,
            "stdout": proc.stdout.strip(),
            "stderr": proc.stderr.strip(),
            "ok": proc.returncode == 0,
        }

    add = _run(["add", "-A"])
    commit = _run(["commit", "-m", f"publish: {datetime.now(UTC).isoformat()}"])
    if not commit["ok"] and "nothing to commit" not in commit["stdout"] + commit["stderr"]:
        commit_ok = False
    else:
        commit_ok = True

    push = _run(["push"])
    return {
        "deployed": push["ok"],
        "add": add,
        "commit": {**commit, "ok": commit_ok},
        "push": push,
        "site_root": str(root),
    }
