/**
 * Task Definitions for Bangle Editor Upgrade Sprint
 * Generated: 2026-08-08
 *
 * Import into TasksPanel.vue and KanbanPanel.vue
 * Status: BACKLOG → TODO → IN_PROGRESS → REVIEW → DONE
 */

export interface SprintTask {
  id: string;
  title: string;
  description: string;
  phase: number;
  component?: string;
  priority: "critical" | "high" | "medium" | "low";
  status: "backlog" | "todo" | "in-progress" | "review" | "done";
  estimatedHours: number;
  assignee?: string;
  dueDate?: string;
  tags: string[];
  checklist: string[];
  dependencies?: string[]; // Task IDs
  notes?: string;
}

export const BANGLE_UPGRADE_TASKS: SprintTask[] = [
  // ─── PHASE 1: Workspace Tree ────────────────────────────────────────
  {
    id: "bangle-p1-001",
    title: "Create WorkspaceTree.vue component",
    description:
      "Build collapsible file/folder tree sidebar for document navigation",
    phase: 1,
    component: "WorkspaceTree.vue",
    priority: "critical",
    status: "backlog",
    estimatedHours: 2,
    tags: ["phase-1", "component", "ui", "workspace"],
    checklist: [
      "Render nested folder structure with expand/collapse",
      "Display file icons based on type",
      "Implement hover states and visual feedback",
      "Add breadcrumb path at sidebar top",
      "Style with USX tokens (no hardcoded values)",
      "Test with 100+ files (performance)",
      "Mobile: Convert to modal drawer on small screens",
    ],
    notes: "Foundation component for Phase 1 — all other files depend on this",
  },
  {
    id: "bangle-p1-002",
    title: "Create WorkspaceTreeNode.vue component",
    description: "Individual file/folder item with right-click context menu",
    phase: 1,
    component: "WorkspaceTreeNode.vue",
    priority: "critical",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["phase-1", "component", "ui"],
    checklist: [
      "Create, rename, delete, move context menu items",
      "Handle mouse and touch long-press",
      "Drag-and-drop file reordering",
      "Double-click to open file",
      "Loading spinner during operations",
      "Error toast notifications",
    ],
    dependencies: ["bangle-p1-001"],
  },
  {
    id: "bangle-p1-003",
    title: "Create FileOperations.ts utility",
    description: "API functions for file CRUD operations",
    phase: 1,
    component: "FileOperations.ts",
    priority: "high",
    status: "backlog",
    estimatedHours: 1,
    tags: ["phase-1", "utility", "api"],
    checklist: [
      "createFile(name: string, content?: string)",
      "renameFile(id: string, newName: string)",
      "deleteFile(id: string)",
      "moveFile(id: string, targetFolderId: string)",
      "Error handling and logging",
      "Mock API for testing",
    ],
  },
  {
    id: "bangle-p1-004",
    title: "Create useWorkspaceStore",
    description: "Pinia store for workspace tree state management",
    phase: 1,
    component: "useWorkspaceStore.ts",
    priority: "high",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["phase-1", "store", "state"],
    checklist: [
      "fileTree: FileNode[] state",
      "expandedFolders: Set<string>",
      "selectedFileId: string",
      "breadcrumb: string[] computed",
      "loadWorkspace() action",
      "selectFile(id) mutation",
      "createFile(name) mutation",
      "Persist folder expansion state to localStorage",
    ],
    dependencies: ["bangle-p1-003"],
  },
  {
    id: "bangle-p1-005",
    title: "Refactor EditorPanel layout to 3-column",
    description:
      "Update EditorPanel to include sidebar | editor | research panel",
    phase: 1,
    component: "EditorPanel.vue",
    priority: "critical",
    status: "backlog",
    estimatedHours: 1,
    tags: ["phase-1", "refactor", "layout"],
    checklist: [
      "Import WorkspaceTree component",
      "Change layout from full-width to flex 3-column",
      "Sidebar: 24% width (collapsible on mobile)",
      "Editor: 60% width (grows/shrinks)",
      "Research panel: 16% width (hidden by default)",
      "Resize handles between panes",
      "Persist column widths to localStorage",
    ],
    dependencies: ["bangle-p1-001", "bangle-p1-004"],
  },
  {
    id: "bangle-p1-006",
    title: "Wire file selection to editor",
    description:
      "Connect WorkspaceTree file clicks to BangleEditor content loading",
    phase: 1,
    component: "Integration",
    priority: "critical",
    status: "backlog",
    estimatedHours: 1,
    tags: ["phase-1", "integration", "state"],
    checklist: [
      "Double-click file → useEditorSurface.openFile()",
      "Load markdown content into BangleEditor",
      "Update editor title from filename",
      "Unsaved changes indicator",
      "Auto-save on blur (or debounced)",
      "Handle file not found errors",
    ],
    dependencies: ["bangle-p1-005"],
  },

  // ─── PHASE 2: Frontmatter & Pills ───────────────────────────────────
  {
    id: "bangle-p2-001",
    title: "Create FrontmatterParser.ts utility",
    description: "Parse YAML frontmatter from markdown documents",
    phase: 2,
    component: "FrontmatterParser.ts",
    priority: "high",
    status: "backlog",
    estimatedHours: 1,
    tags: ["phase-2", "utility", "parser"],
    checklist: [
      "extractFrontmatter(markdown: string): {content, frontmatter}",
      "parseFrontmatter(yaml: string): Record<string, any>",
      "stringifyFrontmatter(obj: Record<string, any>): string",
      "Validate YAML syntax",
      "Handle missing frontmatter gracefully",
      "Unit tests (10+ test cases)",
    ],
  },
  {
    id: "bangle-p2-002",
    title: "Create FrontmatterPills.vue component",
    description: "Display frontmatter metadata as visual editable pills",
    phase: 2,
    component: "FrontmatterPills.vue",
    priority: "high",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["phase-2", "component", "ui"],
    checklist: [
      "Render each frontmatter key-value as pill",
      "Format special values: tags as chips, dates readable",
      "Click pill → edit modal or inline input",
      "Drag-and-drop pill reordering",
      'Add/remove pills via "+" button',
      "Color coding by property type (tag, date, status, etc)",
      "Responsive pill wrapping on mobile",
    ],
    dependencies: ["bangle-p2-001"],
  },
  {
    id: "bangle-p2-003",
    title: "Create FrontmatterEditor.vue modal",
    description: "Edit frontmatter via YAML form or visual interface",
    phase: 2,
    component: "FrontmatterEditor.vue",
    priority: "medium",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["phase-2", "component", "modal"],
    checklist: [
      "YAML text editor tab",
      "Visual form builder tab (fields, checkboxes, date pickers)",
      "Template presets (blog post, research, note)",
      "Syntax validation with error messages",
      "Preview of resulting YAML",
      "Save button (validate before save)",
      "Cancel button (discard changes)",
    ],
    dependencies: ["bangle-p2-001", "bangle-p2-002"],
  },
  {
    id: "bangle-p2-004",
    title: "Integrate frontmatter extraction and save",
    description: "Auto-extract frontmatter from editor and sync on changes",
    phase: 2,
    component: "Integration",
    priority: "high",
    status: "backlog",
    estimatedHours: 1,
    tags: ["phase-2", "integration"],
    checklist: [
      "On editor mount: extract frontmatter and display pills",
      "On pill edit: update document frontmatter",
      "On document save: preserve frontmatter in file",
      "Bidirectional sync (edit pills ↔ YAML source)",
      "Debounce auto-save (500ms)",
      "Conflict resolution if edited in both pill and YAML",
    ],
    dependencies: ["bangle-p2-002", "bangle-p2-003"],
  },

  // ─── PHASE 3: Enhanced Toolbar ──────────────────────────────────────
  {
    id: "bangle-p3-001",
    title: "Create EnhancedBangleToolbar.vue",
    description:
      "Full-featured toolbar with 25+ formatting commands and Material Symbols icons",
    phase: 3,
    component: "EnhancedBangleToolbar.vue",
    priority: "high",
    status: "backlog",
    estimatedHours: 2,
    tags: ["phase-3", "component", "toolbar"],
    checklist: [
      "Text formatting section: B, I, U, strikethrough, code, link",
      "Block elements section: H1-H6, quote, bullets, ordered list, code block, table",
      "Structure section: outline, callout, footnote",
      "Research section: scrape, summarize, citation (Phase 6)",
      "Document section: copy-to-binder, variant, archive (Phase 6)",
      "Edit section: undo, redo, mode-toggle",
      "Use Material Symbols for all icons",
      "Tooltips on 300ms hover with keyboard shortcuts",
      "Keyboard shortcut legends (Ctrl+B, Cmd+I, etc)",
      "Mobile: Responsive toolbar (scroll or dropdown menu)",
    ],
  },
  {
    id: "bangle-p3-002",
    title: "Create ToolbarSection.vue component",
    description: "Reusable toolbar section grouping with visual separators",
    phase: 3,
    component: "ToolbarSection.vue",
    priority: "medium",
    status: "backlog",
    estimatedHours: 0.5,
    tags: ["phase-3", "component"],
    checklist: [
      "Render group of toolbar buttons",
      "Vertical divider separator",
      "Flex layout with proper spacing (--usx-spacing-sm)",
      "Responsive grouping on mobile",
    ],
    dependencies: ["bangle-p3-001"],
  },
  {
    id: "bangle-p3-003",
    title: "Create ToolbarButton.vue atom component",
    description: "Reusable icon button with tooltip and active states",
    phase: 3,
    component: "ToolbarButton.vue",
    priority: "medium",
    status: "backlog",
    estimatedHours: 0.5,
    tags: ["phase-3", "component", "atom"],
    checklist: [
      "Icon rendering via <UIcon>",
      "Tooltip on hover",
      "Active/pressed state styling",
      "Disabled state",
      "Click handler with debounce",
      "Keyboard shortcut display in tooltip",
      "USX tokens for all colors and spacing",
    ],
  },
  {
    id: "bangle-p3-004",
    title: "Implement all formatting commands",
    description: "Wire up Bangle commands to toolbar buttons",
    phase: 3,
    component: "BangleEditor.vue",
    priority: "high",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["phase-3", "implementation"],
    checklist: [
      "Bold, Italic, Underline commands",
      "Strikethrough (using Bangle mark)",
      "Link insertion (URL modal)",
      "Heading levels H1-H6 (dropdown)",
      "Block quote, lists, code block",
      "Table insertion",
      "Image insertion (URL or upload)",
      "Horizontal rule",
      "Test all commands with edge cases",
      "Keyboard shortcut handler",
    ],
    dependencies: ["bangle-p3-001", "bangle-p3-003"],
  },
  {
    id: "bangle-p3-005",
    title: "Replace old toolbar with enhanced version",
    description: "Swap out text button toolbar for new EnhancedBangleToolbar",
    phase: 3,
    component: "BangleEditor.vue",
    priority: "high",
    status: "backlog",
    estimatedHours: 0.5,
    tags: ["phase-3", "refactor"],
    checklist: [
      "Remove old toolbar template code",
      "Import EnhancedBangleToolbar",
      "Wire props and events",
      "Verify all buttons work",
      "Check icon rendering",
    ],
    dependencies: ["bangle-p3-004"],
  },

  // ─── PHASE 4: BrowserUI Integration ─────────────────────────────────
  {
    id: "bangle-p4-001",
    title: "Create WebScraperModal.vue component",
    description: "URL input dialog with preview for web scraping",
    phase: 4,
    component: "WebScraperModal.vue",
    priority: "high",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["phase-4", "component", "modal"],
    checklist: [
      "URL input field with validation",
      "Fetch and preview button",
      "Show extracted title, description, content preview",
      "Loading spinner while fetching",
      "Error handling with retry",
      'Cancel and "Create Document" buttons',
      "Auto-populate from BrowserUI card if available",
    ],
  },
  {
    id: "bangle-p4-002",
    title: "Create ResearchDocTemplate.ts utility",
    description: "Generate frontmatter + markdown for research documents",
    phase: 4,
    component: "ResearchDocTemplate.ts",
    priority: "high",
    status: "backlog",
    estimatedHours: 0.5,
    tags: ["phase-4", "utility"],
    checklist: [
      "createResearchDoc(url, title, content, description?)",
      "Auto-generate frontmatter: title, source, date, type, status",
      "Format content as markdown with source attribution",
      "Include canonical URL reference",
      "Return markdown string ready for editor",
    ],
  },
  {
    id: "bangle-p4-003",
    title: "Update BrowserUISurface card click handler",
    description:
      "Redirect card clicks to open in Bangle instead of external link",
    phase: 4,
    component: "BrowserUISurface.vue",
    priority: "high",
    status: "backlog",
    estimatedHours: 1,
    tags: ["phase-4", "refactor", "integration"],
    checklist: [
      "Remove <a href> external link",
      "Add click handler",
      "Open WebScraperModal with card URL",
      'Show "Open in Bangle" confirmation',
      "Create research document on confirm",
      "Navigate to editor with new document",
      'Fallback: "Open original link" button',
    ],
    dependencies: ["bangle-p4-001", "bangle-p4-002"],
  },
  {
    id: "bangle-p4-004",
    title: "API: Implement web scraper backend",
    description: "POST /api/editor/scrape-web endpoint",
    phase: 4,
    component: "Backend",
    priority: "high",
    status: "backlog",
    estimatedHours: 2,
    tags: ["phase-4", "backend", "api"],
    checklist: [
      "Fetch URL with error handling",
      "Parse HTML (cheerio or similar)",
      "Extract title, description, article body",
      "Clean HTML (remove ads, nav, sidebar)",
      "Return structured JSON: {title, description, html, text}",
      "Timeout after 10 seconds",
      "Rate limiting per user",
      "User-Agent header to avoid blocks",
    ],
  },

  // ─── PHASE 5: Web Content Tools ─────────────────────────────────────
  {
    id: "bangle-p5-001",
    title: "Create HtmlToMarkdown.ts utility",
    description: "Convert HTML to Markdown preserving formatting",
    phase: 5,
    component: "HtmlToMarkdown.ts",
    priority: "high",
    status: "backlog",
    estimatedHours: 1,
    tags: ["phase-5", "utility", "parser"],
    checklist: [
      "htmlToMarkdown(html: string): string",
      "Preserve bold, italic, links, lists",
      "Handle tables → markdown table syntax",
      "Convert images → ![alt](url)",
      "Code blocks → triple backtick with language",
      "Handle nested elements",
      "Clean extra whitespace",
      "Unit tests with real HTML samples",
    ],
    dependencies: ["bangle-p4-004"],
  },
  {
    id: "bangle-p5-002",
    title: "Create WebScraper.ts utility",
    description: "Complete scrape pipeline: fetch → parse → convert",
    phase: 5,
    component: "WebScraper.ts",
    priority: "high",
    status: "backlog",
    estimatedHours: 1,
    tags: ["phase-5", "utility"],
    checklist: [
      "scrapeUrl(url: string): Promise<ScrapedContent>",
      "Call backend /api/editor/scrape-web",
      "Convert HTML to Markdown using HtmlToMarkdown",
      "Combine with ResearchDocTemplate",
      "Return markdown + frontmatter ready for editor",
      "Error handling and user feedback",
    ],
    dependencies: ["bangle-p5-001", "bangle-p4-004"],
  },
  {
    id: "bangle-p5-003",
    title: "Integrate web scrape button to toolbar",
    description: 'Add "Web Scrape" button to EnhancedBangleToolbar',
    phase: 5,
    component: "EnhancedBangleToolbar.vue",
    priority: "medium",
    status: "backlog",
    estimatedHours: 1,
    tags: ["phase-5", "integration"],
    checklist: [
      "Add Web Scrape button (language icon)",
      "Click → open WebScraperModal",
      "Modal shows URL input + preview",
      "On confirm: scrape URL and create new document",
      "Insert scraped content at cursor if in editor",
      "Show loading and success notifications",
    ],
    dependencies: ["bangle-p5-002", "bangle-p4-001"],
  },

  // ─── PHASE 6: Research Aggregation ──────────────────────────────────
  {
    id: "bangle-p6-001",
    title: "Create ResearchPanel.vue component",
    description: "Sidebar showing research documents and context",
    phase: 6,
    component: "ResearchPanel.vue",
    priority: "medium",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["phase-6", "component", "research"],
    checklist: [
      "List of research documents from workspace",
      "Multi-select documents (checkboxes)",
      "Document summary preview on hover",
      "Quick actions: Open, Copy URL, Share",
      "Filter by tag or date",
      "Sort by relevance or date",
      "Collapsible sections by research phase",
    ],
  },
  {
    id: "bangle-p6-002",
    title: "Create Summarize tool",
    description: "Select text → AI generates summary → insert into document",
    phase: 6,
    component: "SummarizeModal.vue",
    priority: "medium",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["phase-6", "feature", "research"],
    checklist: [
      'Right-click selection → "Summarize" context menu',
      'Show selected text + "Generating..." spinner',
      "Call backend POST /api/editor/summarize",
      "Display AI summary result",
      "Options: insert as blockquote, section, footnote",
      "Preview before insertion",
      "Cite original selection",
      "Cache summaries per document",
    ],
  },
  {
    id: "bangle-p6-003",
    title: "Create Combine Research tool",
    description: "Multi-select documents → create synthesis document",
    phase: 6,
    component: "CombineResearchModal.vue",
    priority: "medium",
    status: "backlog",
    estimatedHours: 2,
    tags: ["phase-6", "feature", "research"],
    checklist: [
      "ResearchPanel multi-select UI",
      '"Combine Research" button',
      "Modal shows selected documents",
      "Wizard: choose synthesis format (report, list, Venn)",
      "Extract key points from each source",
      "Generate cross-references and citations",
      "Create new synthesis document with structure",
      "Link back to source documents in frontmatter",
    ],
    dependencies: ["bangle-p6-001"],
  },
  {
    id: "bangle-p6-004",
    title: "Create Copy to Binder export",
    description: "Export current document to Binder with versioning",
    phase: 6,
    component: "Integration",
    priority: "medium",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["phase-6", "feature", "export"],
    checklist: [
      'Toolbar button: "Copy to Binder"',
      "Modal: choose destination (project, board, section)",
      "Create snapshot/archive version",
      "Preserve source URL and research metadata",
      "Maintain reference back to original",
      "Show success notification with Binder link",
      "Auto-update Binder timestamp",
    ],
  },
  {
    id: "bangle-p6-005",
    title: "Create Variant branching feature",
    description: "Create parallel version of document with reference to parent",
    phase: 6,
    component: "Integration",
    priority: "low",
    status: "backlog",
    estimatedHours: 1,
    tags: ["phase-6", "feature"],
    checklist: [
      'Toolbar button: "Create Variant"',
      "New document ID with parent reference in frontmatter",
      "Parent and child can sync metadata changes",
      "Show variant chain in ResearchPanel",
      "Diff/compare variants feature",
    ],
  },
  {
    id: "bangle-p6-006",
    title: "Create Citation generator",
    description: "Auto-generate citations from frontmatter source URLs",
    phase: 6,
    component: "CitationGenerator.ts",
    priority: "low",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["phase-6", "utility"],
    checklist: [
      'citationGenerator(url: string, format: "APA"|"MLA"|"Chicago"): string',
      "Detect publication type (article, blog, doc, video)",
      "Extract metadata from URL (og:title, og:author, etc)",
      "Generate formatted citation string",
      'Toolbar button: "Insert Citation"',
      "Cite selection or document source URL",
    ],
  },
  {
    id: "bangle-p6-007",
    title: "API: Implement summarize backend",
    description: "POST /api/editor/summarize endpoint with AI",
    phase: 6,
    component: "Backend",
    priority: "medium",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["phase-6", "backend", "api"],
    checklist: [
      "Accept selected text and context",
      "Call AI router with summarize skill",
      "Return concise summary (max 50% of original length)",
      "Include source attribution in response",
      "Timeout after 10 seconds",
      "Rate limiting per user",
      "Cache results by document + selection hash",
    ],
  },

  // ─── TESTING & POLISH ───────────────────────────────────────────────
  {
    id: "bangle-test-001",
    title: "Unit tests: All utilities",
    description:
      "FrontmatterParser, HtmlToMarkdown, WebScraper, CitationGenerator",
    phase: 0, // Cross-phase testing
    priority: "high",
    status: "backlog",
    estimatedHours: 2,
    tags: ["testing", "qa"],
    checklist: [
      "FrontmatterParser: 15+ test cases",
      "HtmlToMarkdown: 10+ real HTML samples",
      "WebScraper: mock backend responses",
      "CitationGenerator: multiple URL formats",
      "All edge cases and error paths",
      ">85% code coverage",
    ],
  },
  {
    id: "bangle-test-002",
    title: "Component tests: Interactive elements",
    description: "TreeNode, Pills, Toolbar buttons, modals",
    phase: 0, // Cross-phase testing
    priority: "high",
    status: "backlog",
    estimatedHours: 2,
    tags: ["testing", "qa"],
    checklist: [
      "WorkspaceTreeNode: click, context menu, drag-drop",
      "FrontmatterPills: click to edit, drag reorder",
      "ToolbarButtons: click, hover, active states",
      "Modals: open, input, cancel, submit",
      "Keyboard navigation and shortcuts",
      "Focus management",
    ],
  },
  {
    id: "bangle-test-003",
    title: "E2E tests: Complete workflows",
    description: "Create → Edit → Export workflow",
    phase: 0, // Cross-phase testing
    priority: "high",
    status: "backlog",
    estimatedHours: 2,
    tags: ["testing", "qa"],
    checklist: [
      "Create new document in workspace",
      "Edit content with toolbar",
      "Add/edit frontmatter",
      "Save and verify persistence",
      "Export to Binder",
      "BrowserUI card → Bangle workflow",
      "Combine research documents",
    ],
  },
  {
    id: "bangle-test-004",
    title: "Mobile/responsive testing",
    description: "Test all components on mobile devices",
    phase: 0, // Cross-phase testing
    priority: "high",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["testing", "qa", "mobile"],
    checklist: [
      "iOS Safari (iPad, iPhone)",
      "Android Chrome (various screen sizes)",
      "Touch interactions (swipe, long-press)",
      "Portrait and landscape",
      "Sidebar modal drawer on small screens",
      "Toolbar responsive menu",
      "No layout overflow or scrolling glitches",
    ],
  },
  {
    id: "bangle-test-005",
    title: "Dark mode rendering",
    description: "Verify all components in dark theme",
    phase: 0, // Cross-phase testing
    priority: "medium",
    status: "backlog",
    estimatedHours: 1,
    tags: ["testing", "qa", "accessibility"],
    checklist: [
      "All components render in dark mode",
      "Sufficient contrast (WCAG AA)",
      "Icons visible and clear",
      "Buttons and links distinguishable",
      "Text readable without squinting",
    ],
  },
  {
    id: "bangle-test-006",
    title: "Keyboard accessibility audit",
    description: "Test full keyboard navigation and shortcuts",
    phase: 0, // Cross-phase testing
    priority: "medium",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["testing", "qa", "a11y"],
    checklist: [
      "Tab/Shift+Tab navigation flow",
      "Arrow keys in tree and lists",
      "Enter/Space to activate buttons",
      "Escape to close modals",
      "Cmd+J / Ctrl+J for chat bubble",
      "Cmd+S / Ctrl+S for save",
      "All keyboard shortcuts labeled",
      "Focus indicators visible",
    ],
  },

  // ─── DOCUMENTATION & DEPLOYMENT ─────────────────────────────────────
  {
    id: "bangle-doc-001",
    title: "Write component documentation",
    description: "JSDoc comments for all new components and utilities",
    phase: 0, // Cross-phase documentation
    priority: "medium",
    status: "backlog",
    estimatedHours: 1,
    tags: ["documentation"],
    checklist: [
      "@component tags with description",
      "Props and emit documentation",
      "Usage examples",
      "Related components",
      "Dependencies and imports",
    ],
  },
  {
    id: "bangle-doc-002",
    title: "Create user guide: Bangle Editor",
    description: "Documentation for users on using new features",
    phase: 0, // Cross-phase documentation
    priority: "low",
    status: "backlog",
    estimatedHours: 1,
    tags: ["documentation", "user-guide"],
    checklist: [
      "How to use workspace tree",
      "Editing frontmatter metadata",
      "Toolbar formatting commands",
      "Web scraping workflow",
      "Research aggregation tools",
      "Exporting to Binder",
      "Keyboard shortcuts reference",
    ],
  },
  {
    id: "bangle-deploy-001",
    title: "Performance optimization",
    description: "Ensure builds stay under 2 seconds",
    phase: 0, // Cross-phase optimization
    priority: "medium",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["performance", "optimization"],
    checklist: [
      "Profile bundle size",
      "Lazy-load research components",
      "Virtualize tree for 100+ files",
      "Debounce auto-save",
      "Cache frontmatter parsing results",
      "Minimize re-renders",
      "Verify build time < 2s",
    ],
  },
  {
    id: "bangle-deploy-002",
    title: "Final integration & smoke tests",
    description: "Comprehensive testing before production",
    phase: 0, // Cross-phase testing
    priority: "high",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["testing", "qa", "deployment"],
    checklist: [
      "Full build passes with zero errors",
      "No TypeScript errors",
      "No ESLint warnings",
      "Smoke tests pass",
      "No console errors/warnings in dev",
      "Works on both surfaces (workflow + developer)",
      "No performance regressions",
    ],
  },
];

/**
 * Grouped by phase for easy reference
 */
export const BANGLE_TASKS_BY_PHASE = {
  1: BANGLE_UPGRADE_TASKS.filter((t) => t.phase === 1),
  2: BANGLE_UPGRADE_TASKS.filter((t) => t.phase === 2),
  3: BANGLE_UPGRADE_TASKS.filter((t) => t.phase === 3),
  4: BANGLE_UPGRADE_TASKS.filter((t) => t.phase === 4),
  5: BANGLE_UPGRADE_TASKS.filter((t) => t.phase === 5),
  6: BANGLE_UPGRADE_TASKS.filter((t) => t.phase === 6),
};

/**
 * Calculate phase dependencies and critical path
 */
export function getPhasePrerequisites(phase: number): number[] {
  const deps: Record<number, number[]> = {
    1: [],
    2: [1],
    3: [],
    4: [1],
    5: [4],
    6: [1, 2, 4],
  };
  return deps[phase] || [];
}

/**
 * Estimate total hours for phases
 */
export function calculateTotalEstimate(phases: number[]): number {
  return BANGLE_UPGRADE_TASKS.filter((t) => phases.includes(t.phase)).reduce(
    (sum, task) => sum + task.estimatedHours,
    0,
  );
}
