/**
 * Task Definitions for Bangle Editor Upgrade Sprint
 * Generated: 2026-08-08
 *
 * Import into TasksPanel.vue and KanbanPanel.vue
 * Status: BACKLOG → TODO → IN_PROGRESS → REVIEW → DONE
 */

export interface SprintTask {
  id: string;
  title: string;
  description: string;
  phase: number;
  component?: string;
  priority: "critical" | "high" | "medium" | "low";
  status: "backlog" | "todo" | "in-progress" | "review" | "done";
  estimatedHours: number;
  assignee?: string;
  dueDate?: string;
  tags: string[];
  checklist: string[];
  dependencies?: string[]; // Task IDs
  notes?: string;
}

export const BANGLE_UPGRADE_TASKS: SprintTask[] = [
  // ─── PHASE 1: Workspace Tree ────────────────────────────────────────
  {
    id: "bangle-p1-001",
    title: "Create WorkspaceTree.vue component",
    description:
      "Build collapsible file/folder tree sidebar for document navigation",
    phase: 1,
    component: "WorkspaceTree.vue",
    priority: "critical",
    status: "done",
    estimatedHours: 2,
    tags: ["phase-1", "component", "ui", "workspace"],
    checklist: [
      "Render nested folder structure with expand/collapse",
      "Display file icons based on type",
      "Implement hover states and visual feedback",
      "Add breadcrumb path at sidebar top",
      "Style with USX tokens (no hardcoded values)",
      "Test with 100+ files (performance)",
      "Mobile: Convert to modal drawer on small screens",
    ],
    notes: "Foundation component for Phase 1 — all other files depend on this",
  },
  {
    id: "bangle-p1-002",
    title: "Create WorkspaceTreeNode.vue component",
    description: "Individual file/folder item with right-click context menu",
    phase: 1,
    component: "WorkspaceTreeNode.vue",
    priority: "critical",
    status: "done",
    estimatedHours: 1.5,
    tags: ["phase-1", "component", "ui"],
    checklist: [
      "Create, rename, delete, move context menu items",
      "Handle mouse and touch long-press",
      "Drag-and-drop file reordering",
      "Double-click to open file",
      "Loading spinner during operations",
      "Error toast notifications",
    ],
    dependencies: ["bangle-p1-001"],
  },
  {
    id: "bangle-p1-003",
    title: "Create FileOperations.ts utility",
    description: "API functions for file CRUD operations",
    phase: 1,
    component: "FileOperations.ts",
    priority: "high",
    status: "done",
    estimatedHours: 1,
    tags: ["phase-1", "utility", "api"],
    checklist: [
      "createFile(name: string, content?: string)",
      "renameFile(id: string, newName: string)",
      "deleteFile(id: string)",
      "moveFile(id: string, targetFolderId: string)",
      "Error handling and logging",
      "Mock API for testing",
    ],
  },
  {
    id: "bangle-p1-004",
    title: "Create useWorkspaceStore",
    description: "Pinia store for workspace tree state management",
    phase: 1,
    component: "useWorkspaceStore.ts",
    priority: "high",
    status: "done",
    estimatedHours: 1.5,
    tags: ["phase-1", "store", "state"],
    checklist: [
      "fileTree: FileNode[] state",
      "expandedFolders: Set<string>",
      "selectedFileId: string",
      "breadcrumb: string[] computed",
      "loadWorkspace() action",
      "selectFile(id) mutation",
      "createFile(name) mutation",
      "Persist folder expansion state to localStorage",
    ],
    dependencies: ["bangle-p1-003"],
  },
  {
    id: "bangle-p1-005",
    title: "Refactor EditorPanel layout to 3-column",
    description:
      "Update EditorPanel to include sidebar | editor | research panel",
    phase: 1,
    component: "EditorPanel.vue",
    priority: "critical",
    status: "done",
    estimatedHours: 1,
    tags: ["phase-1", "refactor", "layout"],
    checklist: [
      "Import WorkspaceTree component",
      "Change layout from full-width to flex 3-column",
      "Sidebar: 24% width (collapsible on mobile)",
      "Editor: 60% width (grows/shrinks)",
      "Research panel: 16% width (hidden by default)",
      "Resize handles between panes",
      "Persist column widths to localStorage",
    ],
    dependencies: ["bangle-p1-001", "bangle-p1-004"],
  },
  {
    id: "bangle-p1-006",
    title: "Wire file selection to editor",
    description:
      "Connect WorkspaceTree file clicks to BangleEditor content loading",
    phase: 1,
    component: "Integration",
    priority: "critical",
    status: "done",
    estimatedHours: 1,
    tags: ["phase-1", "integration", "state"],
    checklist: [
      "Double-click file → useEditorSurface.openFile()",
      "Load markdown content into BangleEditor",
      "Update editor title from filename",
      "Unsaved changes indicator",
      "Auto-save on blur (or debounced)",
      "Handle file not found errors",
    ],
    dependencies: ["bangle-p1-005"],
  },

  // ─── PHASE 2: Frontmatter & Pills ───────────────────────────────────
  {
    id: "bangle-p2-001",
    title: "Create FrontmatterParser.ts utility",
    description: "Parse YAML frontmatter from markdown documents",
    phase: 2,
    component: "FrontmatterParser.ts",
    priority: "high",
    status: "done",
    estimatedHours: 1,
    tags: ["phase-2", "utility", "parser"],
    checklist: [
      "extractFrontmatter(markdown: string): {content, frontmatter}",
      "parseFrontmatter(yaml: string): Record<string, any>",
      "stringifyFrontmatter(obj: Record<string, any>): string",
      "Validate YAML syntax",
      "Handle missing frontmatter gracefully",
      "Unit tests (10+ test cases)",
    ],
  },
  {
    id: "bangle-p2-002",
    title: "Create FrontmatterPills.vue component",
    description: "Display frontmatter metadata as visual editable pills",
    phase: 2,
    component: "FrontmatterPills.vue",
    priority: "high",
    status: "done",
    estimatedHours: 1.5,
    tags: ["phase-2", "component", "ui"],
    checklist: [
      "Render each frontmatter key-value as pill",
      "Format special values: tags as chips, dates readable",
      "Click pill → edit modal or inline input",
      "Drag-and-drop pill reordering",
      'Add/remove pills via "+" button',
      "Color coding by property type (tag, date, status, etc)",
      "Responsive pill wrapping on mobile",
    ],
    dependencies: ["bangle-p2-001"],
  },
  {
    id: "bangle-p2-003",
    title: "Create FrontmatterEditor.vue modal",
    description: "Edit frontmatter via YAML form or visual interface",
    phase: 2,
    component: "FrontmatterEditor.vue",
    priority: "medium",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["phase-2", "component", "modal"],
    checklist: [
      "YAML text editor tab",
      "Visual form builder tab (fields, checkboxes, date pickers)",
      "Template presets (blog post, research, note)",
      "Syntax validation with error messages",
      "Preview of resulting YAML",
      "Save button (validate before save)",
      "Cancel button (discard changes)",
    ],
    dependencies: ["bangle-p2-001", "bangle-p2-002"],
  },
  {
    id: "bangle-p2-004",
    title: "Integrate frontmatter extraction and save",
    description: "Auto-extract frontmatter from editor and sync on changes",
    phase: 2,
    component: "Integration",
    priority: "high",
    status: "done",
    estimatedHours: 1,
    tags: ["phase-2", "integration"],
    checklist: [
      "On editor mount: extract frontmatter and display pills",
      "On pill edit: update document frontmatter",
      "On document save: preserve frontmatter in file",
      "Bidirectional sync (edit pills ↔ YAML source)",
      "Debounce auto-save (500ms)",
      "Conflict resolution if edited in both pill and YAML",
    ],
    dependencies: ["bangle-p2-002", "bangle-p2-003"],
  },

  // ─── PHASE 3: Enhanced Toolbar ──────────────────────────────────────
  {
    id: "bangle-p3-001",
    title: "Create EnhancedBangleToolbar.vue",
    description:
      "Full-featured toolbar with 25+ formatting commands and Material Symbols icons",
    phase: 3,
    component: "EnhancedBangleToolbar.vue",
    priority: "high",
    status: "backlog",
    estimatedHours: 2,
    tags: ["phase-3", "component", "toolbar"],
    checklist: [
      "Text formatting section: B, I, U, strikethrough, code, link",
      "Block elements section: H1-H6, quote, bullets, ordered list, code block, table",
      "Structure section: outline, callout, footnote",
      "Research section: scrape, summarize, citation (Phase 6)",
      "Document section: copy-to-binder, variant, archive (Phase 6)",
      "Edit section: undo, redo, mode-toggle",
      "Use Material Symbols for all icons",
      "Tooltips on 300ms hover with keyboard shortcuts",
      "Keyboard shortcut legends (Ctrl+B, Cmd+I, etc)",
      "Mobile: Responsive toolbar (scroll or dropdown menu)",
    ],
  },
  {
    id: "bangle-p3-002",
    title: "Create ToolbarSection.vue component",
    description: "Reusable toolbar section grouping with visual separators",
    phase: 3,
    component: "ToolbarSection.vue",
    priority: "medium",
    status: "backlog",
    estimatedHours: 0.5,
    tags: ["phase-3", "component"],
    checklist: [
      "Render group of toolbar buttons",
      "Vertical divider separator",
      "Flex layout with proper spacing (--usx-spacing-sm)",
      "Responsive grouping on mobile",
    ],
    dependencies: ["bangle-p3-001"],
  },
  {
    id: "bangle-p3-003",
    title: "Create ToolbarButton.vue atom component",
    description: "Reusable icon button with tooltip and active states",
    phase: 3,
    component: "ToolbarButton.vue",
    priority: "medium",
    status: "backlog",
    estimatedHours: 0.5,
    tags: ["phase-3", "component", "atom"],
    checklist: [
      "Icon rendering via <UIcon>",
      "Tooltip on hover",
      "Active/pressed state styling",
      "Disabled state",
      "Click handler with debounce",
      "Keyboard shortcut display in tooltip",
      "USX tokens for all colors and spacing",
    ],
  },
  {
    id: "bangle-p3-004",
    title: "Implement all formatting commands",
    description: "Wire up Bangle commands to toolbar buttons",
    phase: 3,
    component: "BangleEditor.vue",
    priority: "high",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["phase-3", "implementation"],
    checklist: [
      "Bold, Italic, Underline commands",
      "Strikethrough (using Bangle mark)",
      "Link insertion (URL modal)",
      "Heading levels H1-H6 (dropdown)",
      "Block quote, lists, code block",
      "Table insertion",
      "Image insertion (URL or upload)",
      "Horizontal rule",
      "Test all commands with edge cases",
      "Keyboard shortcut handler",
    ],
    dependencies: ["bangle-p3-001", "bangle-p3-003"],
  },
  {
    id: "bangle-p3-005",
    title: "Replace old toolbar with enhanced version",
    description: "Swap out text button toolbar for new EnhancedBangleToolbar",
    phase: 3,
    component: "BangleEditor.vue",
    priority: "high",
    status: "backlog",
    estimatedHours: 0.5,
    tags: ["phase-3", "refactor"],
    checklist: [
      "Remove old toolbar template code",
      "Import EnhancedBangleToolbar",
      "Wire props and events",
      "Verify all buttons work",
      "Check icon rendering",
    ],
    dependencies: ["bangle-p3-004"],
  },

  // ─── PHASE 4: BrowserUI Integration ─────────────────────────────────
  {
    id: "bangle-p4-001",
    title: "Create WebScraperModal.vue component",
    description: "URL input dialog with preview for web scraping",
    phase: 4,
    component: "WebScraperModal.vue",
    priority: "high",
    status: "done",
    estimatedHours: 1.5,
    tags: ["phase-4", "component", "modal"],
    checklist: [
      "URL input field with validation",
      "Fetch and preview button",
      "Show extracted title, description, content preview",
      "Loading spinner while fetching",
      "Error handling with retry",
      'Cancel and "Create Document" buttons',
      "Auto-populate from BrowserUI card if available",
    ],
  },
  {
    id: "bangle-p4-002",
    title: "Create ResearchDocTemplate.ts utility",
    description: "Generate frontmatter + markdown for research documents",
    phase: 4,
    component: "ResearchDocTemplate.ts",
    priority: "high",
    status: "done",
    estimatedHours: 0.5,
    tags: ["phase-4", "utility"],
    checklist: [
      "createResearchDoc(url, title, content, description?)",
      "Auto-generate frontmatter: title, source, date, type, status",
      "Format content as markdown with source attribution",
      "Include canonical URL reference",
      "Return markdown string ready for editor",
    ],
  },
  {
    id: "bangle-p4-003",
    title: "Update BrowserUISurface card click handler",
    description:
      "Redirect card clicks to open in Bangle instead of external link",
    phase: 4,
    component: "BrowserUISurface.vue",
    priority: "high",
    status: "done",
    estimatedHours: 1,
    tags: ["phase-4", "refactor", "integration"],
    checklist: [
      "Remove <a href> external link",
      "Add click handler",
      "Open WebScraperModal with card URL",
      'Show "Open in Bangle" confirmation',
      "Create research document on confirm",
      "Navigate to editor with new document",
      'Fallback: "Open original link" button',
    ],
    dependencies: ["bangle-p4-001", "bangle-p4-002"],
  },
  {
    id: "bangle-p4-004",
    title: "API: Implement web scraper backend",
    description: "POST /api/editor/scrape-web endpoint",
    phase: 4,
    component: "Backend",
    priority: "high",
    status: "done",
    estimatedHours: 2,
    tags: ["phase-4", "backend", "api"],
    checklist: [
      "Fetch URL with error handling",
      "Parse HTML (cheerio or similar)",
      "Extract title, description, article body",
      "Clean HTML (remove ads, nav, sidebar)",
      "Return structured JSON: {title, description, html, text}",
      "Timeout after 10 seconds",
      "Rate limiting per user",
      "User-Agent header to avoid blocks",
    ],
  },

  // ─── PHASE 5: Web Content Tools ─────────────────────────────────────
  {
    id: "bangle-p5-001",
    title: "Create HtmlToMarkdown.ts utility",
    description: "Convert HTML to Markdown preserving formatting",
    phase: 5,
    component: "HtmlToMarkdown.ts",
    priority: "high",
    status: "done",
    estimatedHours: 1,
    tags: ["phase-5", "utility", "parser"],
    checklist: [
      "htmlToMarkdown(html: string): string",
      "Preserve bold, italic, links, lists",
      "Handle tables → markdown table syntax",
      "Convert images → ![alt](url)",
      "Code blocks → triple backtick with language",
      "Handle nested elements",
      "Clean extra whitespace",
      "Unit tests with real HTML samples",
    ],
    dependencies: ["bangle-p4-004"],
  },
  {
    id: "bangle-p5-002",
    title: "Create WebScraper.ts utility",
    description: "Complete scrape pipeline: fetch → parse → convert",
    phase: 5,
    component: "WebScraper.ts",
    priority: "high",
    status: "done",
    estimatedHours: 1,
    tags: ["phase-5", "utility"],
    checklist: [
      "scrapeUrl(url: string): Promise<ScrapedContent>",
      "Call backend /api/editor/scrape-web",
      "Convert HTML to Markdown using HtmlToMarkdown",
      "Combine with ResearchDocTemplate",
      "Return markdown + frontmatter ready for editor",
      "Error handling and user feedback",
    ],
    dependencies: ["bangle-p5-001", "bangle-p4-004"],
  },
  {
    id: "bangle-p5-003",
    title: "Integrate web scrape button to toolbar",
    description: 'Add "Web Scrape" button to EnhancedBangleToolbar',
    phase: 5,
    component: "EnhancedBangleToolbar.vue",
    priority: "medium",
    status: "backlog",
    estimatedHours: 1,
    tags: ["phase-5", "integration"],
    checklist: [
      "Add Web Scrape button (language icon)",
      "Click → open WebScraperModal",
      "Modal shows URL input + preview",
      "On confirm: scrape URL and create new document",
      "Insert scraped content at cursor if in editor",
      "Show loading and success notifications",
    ],
    dependencies: ["bangle-p5-002", "bangle-p4-001"],
  },

  // ─── PHASE 6: Research Aggregation ──────────────────────────────────
  {
    id: "bangle-p6-001",
    title: "Create ResearchPanel.vue component",
    description: "Sidebar showing research documents and context",
    phase: 6,
    component: "ResearchPanel.vue",
    priority: "medium",
    status: "done",
    estimatedHours: 1.5,
    tags: ["phase-6", "component", "research"],
    checklist: [
      "List of research documents from workspace",
      "Multi-select documents (checkboxes)",
      "Document summary preview on hover",
      "Quick actions: Open, Copy URL, Share",
      "Filter by tag or date",
      "Sort by relevance or date",
      "Collapsible sections by research phase",
    ],
  },
  {
    id: "bangle-p6-002",
    title: "Create Summarize tool",
    description: "Select text → AI generates summary → insert into document",
    phase: 6,
    component: "SummarizeModal.vue",
    priority: "medium",
    status: "done",
    estimatedHours: 1.5,
    tags: ["phase-6", "feature", "research"],
    checklist: [
      'Right-click selection → "Summarize" context menu',
      'Show selected text + "Generating..." spinner',
      "Call backend POST /api/editor/summarize",
      "Display AI summary result",
      "Options: insert as blockquote, section, footnote",
      "Preview before insertion",
      "Cite original selection",
      "Cache summaries per document",
    ],
  },
  {
    id: "bangle-p6-003",
    title: "Create Combine Research tool",
    description: "Multi-select documents → create synthesis document",
    phase: 6,
    component: "CombineResearchModal.vue",
    priority: "medium",
    status: "backlog",
    estimatedHours: 2,
    tags: ["phase-6", "feature", "research"],
    checklist: [
      "ResearchPanel multi-select UI",
      '"Combine Research" button',
      "Modal shows selected documents",
      "Wizard: choose synthesis format (report, list, Venn)",
      "Extract key points from each source",
      "Generate cross-references and citations",
      "Create new synthesis document with structure",
      "Link back to source documents in frontmatter",
    ],
    dependencies: ["bangle-p6-001"],
  },
  {
    id: "bangle-p6-004",
    title: "Create Copy to Binder export",
    description: "Export current document to Binder with versioning",
    phase: 6,
    component: "Integration",
    priority: "medium",
    status: "done",
    estimatedHours: 1.5,
    tags: ["phase-6", "feature", "export"],
    checklist: [
      'Toolbar button: "Copy to Binder"',
      "Modal: choose destination (project, board, section)",
      "Create snapshot/archive version",
      "Preserve source URL and research metadata",
      "Maintain reference back to original",
      "Show success notification with Binder link",
      "Auto-update Binder timestamp",
    ],
  },
  {
    id: "bangle-p6-005",
    title: "Create Variant branching feature",
    description: "Create parallel version of document with reference to parent",
    phase: 6,
    component: "Integration",
    priority: "low",
    status: "backlog",
    estimatedHours: 1,
    tags: ["phase-6", "feature"],
    checklist: [
      'Toolbar button: "Create Variant"',
      "New document ID with parent reference in frontmatter",
      "Parent and child can sync metadata changes",
      "Show variant chain in ResearchPanel",
      "Diff/compare variants feature",
    ],
  },
  {
    id: "bangle-p6-006",
    title: "Create Citation generator",
    description: "Auto-generate citations from frontmatter source URLs",
    phase: 6,
    component: "CitationGenerator.ts",
    priority: "low",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["phase-6", "utility"],
    checklist: [
      'citationGenerator(url: string, format: "APA"|"MLA"|"Chicago"): string',
      "Detect publication type (article, blog, doc, video)",
      "Extract metadata from URL (og:title, og:author, etc)",
      "Generate formatted citation string",
      'Toolbar button: "Insert Citation"',
      "Cite selection or document source URL",
    ],
  },
  {
    id: "bangle-p6-007",
    title: "API: Implement summarize backend",
    description: "POST /api/editor/summarize endpoint with AI",
    phase: 6,
    component: "Backend",
    priority: "medium",
    status: "done",
    estimatedHours: 1.5,
    tags: ["phase-6", "backend", "api"],
    checklist: [
      "Accept selected text and context",
      "Call AI router with summarize skill",
      "Return concise summary (max 50% of original length)",
      "Include source attribution in response",
      "Timeout after 10 seconds",
      "Rate limiting per user",
      "Cache results by document + selection hash",
    ],
  },

  // ─── TESTING & POLISH ───────────────────────────────────────────────
  {
    id: "bangle-test-001",
    title: "Unit tests: All utilities",
    description:
      "FrontmatterParser, HtmlToMarkdown, WebScraper, CitationGenerator",
    phase: 0, // Cross-phase testing
    priority: "high",
    status: "backlog",
    estimatedHours: 2,
    tags: ["testing", "qa"],
    checklist: [
      "FrontmatterParser: 15+ test cases",
      "HtmlToMarkdown: 10+ real HTML samples",
      "WebScraper: mock backend responses",
      "CitationGenerator: multiple URL formats",
      "All edge cases and error paths",
      ">85% code coverage",
    ],
  },
  {
    id: "bangle-test-002",
    title: "Component tests: Interactive elements",
    description: "TreeNode, Pills, Toolbar buttons, modals",
    phase: 0, // Cross-phase testing
    priority: "high",
    status: "backlog",
    estimatedHours: 2,
    tags: ["testing", "qa"],
    checklist: [
      "WorkspaceTreeNode: click, context menu, drag-drop",
      "FrontmatterPills: click to edit, drag reorder",
      "ToolbarButtons: click, hover, active states",
      "Modals: open, input, cancel, submit",
      "Keyboard navigation and shortcuts",
      "Focus management",
    ],
  },
  {
    id: "bangle-test-003",
    title: "E2E tests: Complete workflows",
    description: "Create → Edit → Export workflow",
    phase: 0, // Cross-phase testing
    priority: "high",
    status: "backlog",
    estimatedHours: 2,
    tags: ["testing", "qa"],
    checklist: [
      "Create new document in workspace",
      "Edit content with toolbar",
      "Add/edit frontmatter",
      "Save and verify persistence",
      "Export to Binder",
      "BrowserUI card → Bangle workflow",
      "Combine research documents",
    ],
  },
  {
    id: "bangle-test-004",
    title: "Mobile/responsive testing",
    description: "Test all components on mobile devices",
    phase: 0, // Cross-phase testing
    priority: "high",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["testing", "qa", "mobile"],
    checklist: [
      "iOS Safari (iPad, iPhone)",
      "Android Chrome (various screen sizes)",
      "Touch interactions (swipe, long-press)",
      "Portrait and landscape",
      "Sidebar modal drawer on small screens",
      "Toolbar responsive menu",
      "No layout overflow or scrolling glitches",
    ],
  },
  {
    id: "bangle-test-005",
    title: "Dark mode rendering",
    description: "Verify all components in dark theme",
    phase: 0, // Cross-phase testing
    priority: "medium",
    status: "backlog",
    estimatedHours: 1,
    tags: ["testing", "qa", "accessibility"],
    checklist: [
      "All components render in dark mode",
      "Sufficient contrast (WCAG AA)",
      "Icons visible and clear",
      "Buttons and links distinguishable",
      "Text readable without squinting",
    ],
  },
  {
    id: "bangle-test-006",
    title: "Keyboard accessibility audit",
    description: "Test full keyboard navigation and shortcuts",
    phase: 0, // Cross-phase testing
    priority: "medium",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["testing", "qa", "a11y"],
    checklist: [
      "Tab/Shift+Tab navigation flow",
      "Arrow keys in tree and lists",
      "Enter/Space to activate buttons",
      "Escape to close modals",
      "Cmd+J / Ctrl+J for chat bubble",
      "Cmd+S / Ctrl+S for save",
      "All keyboard shortcuts labeled",
      "Focus indicators visible",
    ],
  },

  // ─── DOCUMENTATION & DEPLOYMENT ─────────────────────────────────────
  {
    id: "bangle-doc-001",
    title: "Write component documentation",
    description: "JSDoc comments for all new components and utilities",
    phase: 0, // Cross-phase documentation
    priority: "medium",
    status: "backlog",
    estimatedHours: 1,
    tags: ["documentation"],
    checklist: [
      "@component tags with description",
      "Props and emit documentation",
      "Usage examples",
      "Related components",
      "Dependencies and imports",
    ],
  },
  {
    id: "bangle-doc-002",
    title: "Create user guide: Bangle Editor",
    description: "Documentation for users on using new features",
    phase: 0, // Cross-phase documentation
    priority: "low",
    status: "backlog",
    estimatedHours: 1,
    tags: ["documentation", "user-guide"],
    checklist: [
      "How to use workspace tree",
      "Editing frontmatter metadata",
      "Toolbar formatting commands",
      "Web scraping workflow",
      "Research aggregation tools",
      "Exporting to Binder",
      "Keyboard shortcuts reference",
    ],
  },
  {
    id: "bangle-deploy-001",
    title: "Performance optimization",
    description: "Ensure builds stay under 2 seconds",
    phase: 0, // Cross-phase optimization
    priority: "medium",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["performance", "optimization"],
    checklist: [
      "Profile bundle size",
      "Lazy-load research components",
      "Virtualize tree for 100+ files",
      "Debounce auto-save",
      "Cache frontmatter parsing results",
      "Minimize re-renders",
      "Verify build time < 2s",
    ],
  },
  {
    id: "bangle-deploy-002",
    title: "Final integration & smoke tests",
    description: "Comprehensive testing before production",
    phase: 0, // Cross-phase testing
    priority: "high",
    status: "backlog",
    estimatedHours: 1.5,
    tags: ["testing", "qa", "deployment"],
    checklist: [
      "Full build passes with zero errors",
      "No TypeScript errors",
      "No ESLint warnings",
      "Smoke tests pass",
      "No console errors/warnings in dev",
      "Works on both surfaces (workflow + developer)",
      "No performance regressions",
    ],
  },
  {
    id: "output-p7-001",
    title: "Backend render.py service",
    description: "JSON → Markdown/HTML converter with per-skill templates",
    phase: 7,
    component: "backend/app/services/render.py",
    priority: "high",
    status: "done",
    estimatedHours: 2,
    tags: ["phase-7", "backend", "layered-output"],
    checklist: [
      "render_markdown(data) → string",
      "render_html(data) → string",
      "_render_summary, _render_health, _render_items helpers",
      "No Jinja2 dependency — pure stdlib",
      "Unit tests for each helper",
    ],
  },
  {
    id: "output-p7-002",
    title: "Backend render_api.py — POST /api/render + GET /api/render/stream",
    description:
      "REST endpoint for rendering + SSE stream for real-time skill events",
    phase: 7,
    component: "backend/app/api/render_api.py",
    priority: "high",
    status: "done",
    estimatedHours: 2,
    tags: ["phase-7", "backend", "sse", "api"],
    checklist: [
      "POST /api/render — format=markdown|html",
      "GET /api/render/stream — SSE endpoint",
      "POST /api/render/event — internal publish",
      "publish_event() Python API for skill runner",
      "25s keepalive ping",
      "Auto-reconnect on client drop",
    ],
  },
  {
    id: "output-p7-003",
    title: "Register render routes in aiohttp app",
    description: "Wire render_api handlers into routes.py",
    phase: 7,
    component: "backend/app/api/routes.py",
    priority: "high",
    status: "done",
    estimatedHours: 0.5,
    tags: ["phase-7", "backend"],
    checklist: [
      "Import render_api handlers",
      "Add POST /api/render",
      "Add GET /api/render/stream",
      "Add POST /api/render/event",
    ],
  },
  {
    id: "output-p7-004",
    title: "Frontend useFeed.ts composable",
    description: "SSE EventSource composable for real-time feed events",
    phase: 7,
    component: "composables/useFeed.ts",
    priority: "high",
    status: "done",
    estimatedHours: 1.5,
    tags: ["phase-7", "frontend", "composable"],
    checklist: [
      "EventSource connection with auto-reconnect (5s)",
      "events ref (last 100 events)",
      "isConnected, error refs",
      "eventsOfType(type) filter",
      "Graceful degradation when backend offline",
      "onMounted/onBeforeUnmount lifecycle",
    ],
  },
  {
    id: "output-p7-005",
    title: "SkillsPanel rendered markdown output",
    description:
      "Replace raw JSON pre block with rendered HTML; add raw/rendered toggle",
    phase: 7,
    component: "surfaces/snackbar/panels/SnackbarSkillsPanel.vue",
    priority: "high",
    status: "done",
    estimatedHours: 1.5,
    tags: ["phase-7", "frontend", "ux"],
    checklist: [
      "RunState.rendered: string field",
      "jsonToMarkdown() client-side renderer",
      "v-html rendered output",
      "Raw JSON toggle button",
      "Styled: table, h3, health percentage",
      "Build passes with zero TS errors",
    ],
  },
  {
    id: "output-p7-006",
    title: "Wire publish_event() into skills runner",
    description: "After each skill run, publish event to SSE stream",
    phase: 7,
    component: "backend/app/api/skills.py",
    priority: "medium",
    status: "done",
    estimatedHours: 1,
    tags: ["phase-7", "backend", "integration"],
    checklist: [
      "Import publish_event from render_api",
      "Call publish_event('skill_complete', data) after success",
      "Call publish_event('skill_error', data) after failure",
      "Include rendered markdown in event data",
    ],
  },

  // ─── PHASE 8: Overlay System ─────────────────────────────────────────
  {
    id: "overlay-p8-001",
    title: "Create AlertOverlay.vue",
    description:
      "System alerts (critical, warning, info, success) as modal or top-right toast",
    phase: 8,
    component: "skills/organisms/AlertOverlay.vue",
    priority: "high",
    status: "done",
    estimatedHours: 2,
    tags: ["phase-8", "overlay", "component"],
    checklist: [
      "Types: critical (blocking modal), warning, info, success",
      "Icon per type: warning, error, check_circle, info",
      "Action buttons: Dismiss, Retry, View Logs",
      "Blocking overlay for critical (cannot dismiss by clicking outside)",
      "Auto-dismiss for non-critical (configurable timeout)",
      "USX tokens only",
    ],
  },
  {
    id: "overlay-p8-002",
    title: "Create ToastOverlay.vue",
    description: "Transient bottom-right toast notifications for feed events",
    phase: 8,
    component: "skills/molecules/ToastOverlay.vue",
    priority: "high",
    status: "done",
    estimatedHours: 2,
    tags: ["phase-8", "overlay", "toast"],
    checklist: [
      "Stack of toasts in bottom-right corner",
      "Auto-dismiss after 5s (configurable)",
      "Skill complete: '✅ audit complete' → click to view results",
      "Task created: '📋 New task...' → click to open task",
      "Slide-in animation, slide-out on dismiss",
      "Max 3 toasts visible (queue remaining)",
    ],
  },
  {
    id: "overlay-p8-003",
    title: "Create useToast.ts composable",
    description: "Toast queue: add, remove, auto-dismiss, dedup",
    phase: 8,
    component: "composables/useToast.ts",
    priority: "high",
    status: "done",
    estimatedHours: 1,
    tags: ["phase-8", "composable"],
    checklist: [
      "toast(msg, type?, duration?) → id",
      "dismiss(id)",
      "Auto-dismiss timer per toast",
      "Global singleton (shared across components)",
      "Integrate with useFeed events",
    ],
  },
  {
    id: "overlay-p8-004",
    title: "Create PopupOverlay.vue",
    description: "Generic modal for confirmations, forms, S-page fallbacks",
    phase: 8,
    component: "skills/organisms/PopupOverlay.vue",
    priority: "medium",
    status: "done",
    estimatedHours: 2,
    tags: ["phase-8", "overlay", "modal"],
    checklist: [
      "Header (title + close)",
      "Body slot (Markdown, form, or arbitrary content)",
      "Footer: action buttons",
      "Backdrop blur overlay",
      "useOverlay.ts integration",
      "S-page fallback content",
      "Skill confirmation dialog",
    ],
  },
  {
    id: "overlay-p8-005",
    title: "Create StoriesOverlay.vue",
    description:
      "Marp-style slide presentation overlay for onboarding/tutorials",
    phase: 8,
    component: "skills/organisms/StoriesOverlay.vue",
    priority: "medium",
    status: "done",
    estimatedHours: 3,
    tags: ["phase-8", "overlay", "stories"],
    checklist: [
      "Full-screen slide container",
      "Previous/Next navigation buttons",
      "Progress bar and slide indicator (1/5)",
      "Slide content: Markdown rendered",
      "Transitions: slide or fade between pages",
      "Close button (escape key)",
      "Story data format: title, slides[]",
      "Onboarding story: first-visit trigger",
    ],
  },
  {
    id: "overlay-p8-006",
    title: "Create useOverlay.ts composable",
    description: "Centralized state for all overlay types",
    phase: 8,
    component: "composables/useOverlay.ts",
    priority: "high",
    status: "done",
    estimatedHours: 1,
    tags: ["phase-8", "composable"],
    checklist: [
      "showAlert(type, title, message, actions?)",
      "showPopup(title, content, actions?)",
      "showStories(slides[])",
      "dismiss() — close active overlay",
      "active ref: current overlay type",
      "Singleton pattern",
    ],
  },
  {
    id: "overlay-p8-007",
    title: "Mount overlay layer in App.vue (both surfaces)",
    description: "Add OverlayLayer root component with all overlays",
    phase: 8,
    component: "App.vue",
    priority: "high",
    status: "done",
    estimatedHours: 1,
    tags: ["phase-8", "integration"],
    checklist: [
      "Create OverlayLayer.vue wrapper",
      "Include: ChatBubble, ToastOverlay, AlertOverlay, PopupOverlay, StoriesOverlay",
      "Mount in uCore App.vue",
      "Mount in the uCore UI Hub",
      "z-index stack: toast 1100, alert 1200, popup 1300, stories 1400",
    ],
  },

  // ─── PHASE 9: uDos Markdown Universe ────────────────────────────────
  {
    id: "markdown-p9-001",
    title: "Create markdownRenderer.ts utility",
    description:
      "Format-aware markdown router: prose | story | game | publish | print",
    phase: 9,
    component: "utils/markdownRenderer.ts",
    priority: "high",
    status: "done",
    estimatedHours: 2,
    tags: ["phase-9", "markdown", "utility"],
    checklist: [
      "renderDocument(markdown) → { html, format, frontmatter }",
      "Detect format from frontmatter or file extension",
      "Route to format-specific renderer",
      "Prose: marked.js with GFM",
      "Story: Marp Core (if available, graceful fallback)",
      "Game: GridCore stub",
      "Callout support: > [!NOTE], > [!WARNING], > [!TIP]",
      "Mermaid diagram blocks",
      "KaTeX math blocks",
    ],
  },
  {
    id: "markdown-p9-002",
    title: "Integrate prose renderer into BangleEditor/EditorPanel",
    description: "Preview tab uses marked.js to render prose markdown",
    phase: 9,
    component: "EditorPanel.vue",
    priority: "high",
    status: "done",
    estimatedHours: 1.5,
    tags: ["phase-9", "frontend", "editor"],
    checklist: [
      "Install marked.js (or use lite version)",
      "Add preview mode to EditorPanel",
      "Render markdown body (not frontmatter) in preview",
      "Toggle button: Edit | Preview",
      "Mermaid diagram rendering",
      "Callout styling",
    ],
  },
  {
    id: "markdown-p9-003",
    title: "Story renderer (Marp Core integration)",
    description: "Slide-deck format for .slide.md files using Marp Core",
    phase: 9,
    component: "utils/storyRenderer.ts",
    priority: "medium",
    status: "done",
    estimatedHours: 3,
    tags: ["phase-9", "story", "marp"],
    checklist: [
      "@marp-team/marp-core dependency",
      "renderStory(markdown) → { slides: string[], css: string }",
      "usx-dark and usx-light themes",
      "Slide separator (---) parsing",
      "Custom class support (<!-- _class: lead -->)",
      "SlideViewer.vue component (navigation, progress)",
    ],
  },
  {
    id: "markdown-p9-004",
    title: "StoriesOverlay uses Story renderer",
    description: "Wire Marp story renderer into StoriesOverlay component",
    phase: 9,
    component: "StoriesOverlay.vue",
    priority: "medium",
    status: "backlog",
    estimatedHours: 1,
    tags: ["phase-9", "story", "overlay"],
    checklist: [
      "Accept slides as either string[] or markdown string",
      "Render each slide using Marp if available",
      "Fall back to prose renderer",
      "Apply usx-dark/light theme CSS",
    ],
    dependencies: ["overlay-p8-005", "markdown-p9-003"],
  },
  {
    id: "markdown-p9-005",
    title: "Game renderer stub (GridCore integration)",
    description: "Route .game.md files to GridCore renderer",
    phase: 9,
    component: "utils/gameRenderer.ts",
    priority: "low",
    status: "done",
    estimatedHours: 4,
    tags: ["phase-9", "game", "gridcore"],
    checklist: [
      "Parse YAML blocks: sprites, locations, dialogues",
      "GridCore canvas mount",
      "Basic movement (n/s/e/w)",
      "Location description rendering",
      "Dialogue tree display",
    ],
    notes: "Depends on GridCore surface being available",
  },
  {
    id: "markdown-p9-006",
    title: "File extension → renderer routing",
    description: "Detect .slide.md, .game.md, .publish.md from workspace tree",
    phase: 9,
    component: "stores/workspace.ts",
    priority: "medium",
    status: "done",
    estimatedHours: 1,
    tags: ["phase-9", "integration"],
    checklist: [
      "WorkspaceTree: detect special extensions",
      "Pass rendererHint to EditorPanel on open",
      "EditorPanel: render with correct renderer",
      "File icons: slide.md → slideshow, game.md → sports_esports",
    ],
  },

  // ─── SPRINT 2: System Integration & Polish (phase 20) ───────────────
  {
    id: "s2-001",
    phase: 20,
    title: "Wire render_api routes",
    description:
      "Register /api/render, /api/render/stream, /api/render/event in routes.py",
    priority: "critical",
    status: "done",
    estimatedHours: 0.5,
    tags: ["sprint-2", "backend"],
    checklist: [
      "Import render_api handlers",
      "Register 3 routes",
      "Smoke test SSE",
    ],
  },
  {
    id: "s2-002",
    phase: 20,
    title: "Wire publish_event() into skill runner",
    description: "After skill run, broadcast SSE event with rendered output",
    priority: "high",
    status: "done",
    estimatedHours: 1,
    tags: ["sprint-2", "backend"],
    checklist: [
      "Import publish_event",
      "Call after success",
      "Include rendered markdown",
    ],
  },
  {
    id: "s2-003",
    phase: 20,
    title: "Register editor_api routes",
    description: "POST /api/editor/scrape-web, /summarize, /save-to-binder",
    priority: "high",
    status: "done",
    estimatedHours: 0.5,
    tags: ["sprint-2", "backend"],
    checklist: ["3 routes registered", "Smoke test each"],
  },
  {
    id: "s2-004",
    phase: 20,
    title: "Mount ChatBubble in OverlayLayer (both surfaces)",
    description: "ChatBubble.vue created but unmounted — wire with /api/chat",
    priority: "critical",
    status: "done",
    estimatedHours: 1.5,
    tags: ["sprint-2", "chat"],
    checklist: [
      "uCore OverlayLayer wired",
      "uCore OverlayLayer wired",
      "sendChatMessage() functional",
    ],
  },
  {
    id: "s2-005",
    phase: 20,
    title: "Phase 5 — HtmlToMarkdown.ts",
    description:
      "Convert HTML → Markdown preserving tables, code, lists, images (no deps)",
    priority: "high",
    status: "done",
    estimatedHours: 2,
    tags: ["sprint-2", "phase-5"],
    checklist: [
      "htmlToMarkdown(html)→string",
      "Tables→GFM",
      "Skip nav/header/footer",
    ],
  },
  {
    id: "s2-006",
    phase: 20,
    title: "Phase 5 — editor_api.py scrape endpoint",
    description:
      "POST /api/editor/scrape-web — aiohttp fetch + article extraction",
    priority: "high",
    status: "done",
    estimatedHours: 2,
    tags: ["sprint-2", "phase-5", "backend"],
    checklist: [
      "Fetch URL",
      "Extract title/desc/text",
      "Regex-based extraction (no BeautifulSoup)",
    ],
  },
  {
    id: "s2-007",
    phase: 20,
    title: "Phase 6 — ResearchPanel.vue",
    description:
      "Right sidebar: research docs, summarize, copy-to-binder actions",
    priority: "high",
    status: "done",
    estimatedHours: 2,
    tags: ["sprint-2", "phase-6"],
    checklist: [
      "Filter by type:research",
      "Summarize action",
      "Copy to Binder action",
    ],
  },
  {
    id: "s2-008",
    phase: 20,
    title: "Phase 6 — SummarizeModal.vue",
    description:
      "Textarea + style toggle + /api/editor/summarize + insert into doc",
    priority: "high",
    status: "done",
    estimatedHours: 2,
    tags: ["sprint-2", "phase-6"],
    checklist: [
      "Pre-fill with body",
      "Bullets/paragraph styles",
      "Insert as ## Summary",
    ],
  },
  {
    id: "s2-009",
    phase: 20,
    title: "Phase 6 — ResearchPanel in EditorPanel",
    description: "Science icon toggle, right column slide-in, 200px width",
    priority: "high",
    status: "done",
    estimatedHours: 1,
    tags: ["sprint-2", "phase-6"],
    checklist: ["Toggle button wired", "Slide transition matches sidebar"],
  },

  // ─── SPRINT 3: Authentication & User Profiles (phase 30) ────────────
  {
    id: "s3-001",
    phase: 30,
    title: "User identity integration",
    description: "GET /api/identity/me → show user in GlobalToolbar",
    priority: "high",
    status: "backlog",
    estimatedHours: 3,
    tags: ["sprint-3", "auth"],
    checklist: [
      "useIdentityStore",
      "Avatar/name in toolbar",
      "Unauthenticated state",
    ],
  },
  {
    id: "s3-002",
    phase: 30,
    title: "Per-user workspace persistence",
    description: "Server-side file tree via GET/POST /api/workspace/tree",
    priority: "high",
    status: "done",
    estimatedHours: 4,
    tags: ["sprint-3", "storage"],
    checklist: [
      "API integration",
      "Optimistic updates",
      "Conflict resolution",
      "Offline fallback",
    ],
  },
  {
    id: "s3-003",
    phase: 30,
    title: "Settings sync across surfaces",
    description:
      "POST /api/user/preferences — sync theme/font/model between surfaces",
    priority: "medium",
    status: "backlog",
    estimatedHours: 2,
    tags: ["sprint-3", "settings"],
    checklist: [
      "Save to backend",
      "Load on mount",
      "Migrate from localStorage",
    ],
  },
  {
    id: "s3-004",
    phase: 30,
    title: "Chat history persistence",
    description: "Save chat conversations to backend per user",
    priority: "medium",
    status: "backlog",
    estimatedHours: 2,
    tags: ["sprint-3", "chat"],
    checklist: [
      "POST /api/chat/history",
      "Restore on reopen",
      "Clear history button",
    ],
  },
  {
    id: "s3-005",
    phase: 30,
    title: "Workspace file API backend",
    description:
      "CRUD endpoints for workspace files (create, read, update, delete)",
    priority: "high",
    status: "done",
    estimatedHours: 5,
    tags: ["sprint-3", "backend", "api"],
    checklist: [
      "GET /api/workspace/files",
      "POST/PUT/DELETE",
      "File content storage (vault or DB)",
      "Access control per user",
    ],
  },

  // ─── SPRINT 4: Mobile PWA & Offline (phase 40) ──────────────────────
  {
    id: "s4-001",
    phase: 40,
    title: "Service worker + offline-first workspace",
    description: "vite-plugin-pwa with workbox cache strategies",
    priority: "medium",
    status: "backlog",
    estimatedHours: 4,
    tags: ["sprint-4", "pwa"],
    checklist: [
      "Install vite-plugin-pwa",
      "Cache app shell",
      "Offline indicator",
      "Sync queue",
    ],
  },
  {
    id: "s4-002",
    phase: 40,
    title: "Mobile gesture navigation",
    description:
      "useSwipe() composable — swipe right/left for sidebar on touch devices",
    priority: "medium",
    status: "backlog",
    estimatedHours: 3,
    tags: ["sprint-4", "mobile"],
    checklist: ["useSwipe composable", "Sidebar open/close", "Tab scroll"],
  },
  {
    id: "s4-003",
    phase: 40,
    title: "Mobile toolbar collapse",
    description:
      "BangleEditor toolbar → icon-only on < 640px with overflow menu",
    priority: "medium",
    status: "backlog",
    estimatedHours: 2,
    tags: ["sprint-4", "mobile", "toolbar"],
    checklist: [
      "useBreakpoint composable",
      "4 primary + overflow",
      "44px touch targets",
    ],
  },
  {
    id: "s4-004",
    phase: 40,
    title: "PWA install prompt",
    description:
      "'Add to Home Screen' banner after 30s dwell, remembers preference",
    priority: "low",
    status: "backlog",
    estimatedHours: 1,
    tags: ["sprint-4", "pwa"],
    checklist: ["beforeinstallprompt", "30s dwell", "Success toast"],
  },
];

/**
 * Grouped by phase for easy reference
 */
export const BANGLE_TASKS_BY_PHASE = {
  1: BANGLE_UPGRADE_TASKS.filter((t) => t.phase === 1),
  2: BANGLE_UPGRADE_TASKS.filter((t) => t.phase === 2),
  3: BANGLE_UPGRADE_TASKS.filter((t) => t.phase === 3),
  4: BANGLE_UPGRADE_TASKS.filter((t) => t.phase === 4),
  5: BANGLE_UPGRADE_TASKS.filter((t) => t.phase === 5),
  6: BANGLE_UPGRADE_TASKS.filter((t) => t.phase === 6),
  7: BANGLE_UPGRADE_TASKS.filter((t) => t.phase === 7),
  8: BANGLE_UPGRADE_TASKS.filter((t) => t.phase === 8),
  9: BANGLE_UPGRADE_TASKS.filter((t) => t.phase === 9),
  20: BANGLE_UPGRADE_TASKS.filter((t) => t.phase === 20), // Sprint 2
  30: BANGLE_UPGRADE_TASKS.filter((t) => t.phase === 30), // Sprint 3
  40: BANGLE_UPGRADE_TASKS.filter((t) => t.phase === 40), // Sprint 4
};

/**
 * Canonical counts derived from task objects. Consumers and documentation
 * should use this summary instead of counting status text in this source file.
 */
export const BANGLE_TASK_SUMMARY = Object.freeze(
  BANGLE_UPGRADE_TASKS.reduce(
    (summary, task) => {
      summary.total += 1;
      summary[task.status] += 1;
      return summary;
    },
    {
      total: 0,
      backlog: 0,
      todo: 0,
      "in-progress": 0,
      review: 0,
      done: 0,
    } as Record<SprintTask["status"] | "total", number>,
  ),
);

/**
 * Calculate phase dependencies and critical path
 */
export function getPhasePrerequisites(phase: number): number[] {
  const deps: Record<number, number[]> = {
    1: [],
    2: [1],
    3: [],
    4: [1],
    5: [4],
    6: [1, 2, 4],
  };
  return deps[phase] || [];
}

/**
 * Estimate total hours for phases
 */
export function calculateTotalEstimate(phases: number[]): number {
  return BANGLE_UPGRADE_TASKS.filter((t) => phases.includes(t.phase)).reduce(
    (sum, task) => sum + task.estimatedHours,
    0,
  );
}
